# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.9.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.3.2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup environment
      run: yarn install
    - name: Build
      run: yarn build
    - name: Unit Tests
      run: yarn test
    - name: Unit Tests Coverage generation
      run: yarn coverage
    - name: Generate coverage code
      uses: codecov/codecov-action@v1
      with:
        file: ./output/coverage/jest/clover.xml
        directory: ./output/coverage/jest/
        flags: unittest
        name: codecov-umbrella
        fail_ci_if_error: true
        path_to_write_report: codecov_report.gz